### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by nhabbott** [alpacahq/Momentum-Trading-Example#17]
I get this error as soon as the script attempts to buy or sell any stock. Not sure why, as the code I added and the code I modified all look fine to me.

```
Watching 167 symbols.
Task exception was never retrieved
future: <Task finished name='Task-9' coro=<StreamConn._consume_msg() done, defined at C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py:99> exception=TypeError("'int' object is not subscriptable")>
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py", line 103, in _consume_msg
    await self._dispatch(data)
  File "C:\Python38\lib\site-packages\alpaca_trade_api\polygon\streamconn.py", line 240, in _dispatch
    await handler(self, channel, ent)
  File "momentum.py", line 251, in handle_second_bar
    if (daily_pct_change > .04 and data.close > high_15m and volume_today[symbol] > 30000):
TypeError: 'int' object is not subscriptable
```

**Comment by nhabbott** [comment]
Added the issue to the main repo as I believe that is where the problem is.
