### ISSUE TITLE
 AttributeError: 'REST' object has no attribute 'historic_agg'

### ISSUE THREAD

**Issue by PipArmy** [alpacahq/Momentum-Trading-Example#19]
Getting current ticker data...
Success.
Tracking 106 symbols.
Getting historical data...
Traceback (most recent call last):
  File "algo.py", line 396, in <module>
    run(get_tickers(), market_open, market_close)
  File "algo.py", line 87, in run
    minute_history = get_1000m_history_data(symbols)
  File "algo.py", line 38, in get_1000m_history_data
    minute_history[symbol] = api.polygon.historic_agg(
AttributeError: 'REST' object has no attribute 'historic_agg'

**Comment by jbarr8** [comment]
See the discussion here to help out with this. 
https://github.com/alpacahq/Momentum-Trading-Example/issues/14
